@url = http://localhost:5007
@orderId = 069daf93-d76a-4ccc-a130-984ce1158850
@customerId = 3ecce964-6ba3-41e2-973c-ca3cb78609f3
@parcelId = c2ab6285-eea4-454d-97dc-eb17725575b6

###
GET {{url}}/orders?customerId={{customerId}}

###
GET {{url}}/orders/{{orderId}}

###
POST {{url}}/orders

{
  "customerId": "{{customerId}}"
}

###
DELETE {{url}}/orders/{{orderId}}

###
POST {{url}}/orders/{{orderId}}/parcels

{
  "orderId": "{{orderId}}",
  "parcelId": "{{parcelId}}"
}

###
DELETE {{url}}/orders/{{orderId}}/parcels/{{parcelId}}
